[stations]
Tamsui = ["Hongshulin"]
Hongshulin = ["Tamsui", "Zhuwei"]
k = ["i", "m", "l"]
m = ["k"]
l = ["k"]
o = ["n"]
n = ["o"]


[lines]
brown = ["Taipei Zoo", "Muzha", "Wanfang Community", "Wanfang Hospital", "Xinhai", "Linguang", "Liuzhangli", "Technology Building", "Daan", "Zhongxiao Fuxing", "Nanjing Fuxing", "Zhongshan Junior High School", "Songshan Airport", "Dazhi", "Jiannan Rd.", "Xihu", "Gangqian", "Wende", "Neihu", "Dahu Park", "Huzhou", "Donghu", "Nangan Software Park", "Taipei Nangan Exhibition Center"]
red = ["Xiangshan", "Taipei 101 - World Trade Center", "Xinyi Anhe", "Daan", "Daan Park", "Dongmen", "Chiang Kai-Shek Memorial Hall", "NTU Hospital", "Taipei Main Station", "Zhongshan", "Shuanglian", "Minquan W. Rd.", "Yuanshan", "Jiantan", "Shilin", "Zhishan", "Mingde", "Shipai", "Qilian", "Qiyan", "Beitou", "Fuxinggang", "Zhongyi", "Guandu", "Zhuwei", "Hongshulin", "Tamsui"]
green = ["Xindian", "Xindian District Office", "Qizhang", "Dapinglin", "Jingmei", "Wanlong", "Gongguan", "Taipower Building", "Guting", "Chiang Kai-Shek Memorial Hall Xiaonanmen", "Ximen", "Beimen", "Zhongshan", "Songjiang Nanjing", "Nanjing Fuxing", "Taipei Arena", "Nanjing Sanmin", "Songshan"]
orange = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
blue = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Taipei Nangan Exhibition Center"]
yellow = ["Dapinglin", "Shisizhang", "Xiulang Bridge", "Jingping", "Jingan", "Zhonghe", "Qiaohe", "Zhongyuan", "Banxin", "Banqiao", "Xinpu", "Xinpu Minsheng", "Touqianzhuang", "Xinfu", "New Taipei Industrial Park"]
