import collections


if __name__ == "__main__":
    top_row_count1 = collections.namedtuple('top_row_count1', ['count1'])
    top_count1 = top_row_count1(50)

    # Sets, lists, dicts, and tuples are the 4 basic data structures in Python.

    # Sets in Python are hashsets, so they can't have duplicate values
    top_row_count2 = set((50, 0))
    top_row_count2.add(50)

    # Logo generated by http://www.network-science.de/ascii/ using the "big" font
    ascii_logo = """
 _______    _            _ __  __      _             _   _             _             _             
|__   __|  (_)          (_)  \/  |    | |           | \ | |           (_)           | |            
   | | __ _ _ _ __   ___ _| \  / | ___| |_ _ __ ___ |  \| | __ ___   ___  __ _  __ _| |_ ___  _ __ 
   | |/ _` | | '_ \ / _ \ | |\/| |/ _ \ __| '__/ _ \| . ` |/ _` \ \ / / |/ _` |/ _` | __/ _ \| '__|
   | | (_| | | |_) |  __/ | |  | |  __/ |_| | | (_) | |\  | (_| |\ V /| | (_| | (_| | || (_) | |   
   |_|\__,_|_| .__/ \___|_|_|  |_|\___|\__|_|  \___/|_| \_|\__,_| \_/ |_|\__, |\__,_|\__\___/|_|   
             | |                                                          __/ |                    
             |_|                                                         |___/    
    """


    for _ in range(top_count1.count1):
        print("=", end='')

    for value in top_row_count2:
        for _ in range(value):
            print("=", end='')


    print(ascii_logo)
